name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the bug? What did you expect vs. what happened?
      placeholder: When I call create_payment(...), I expected... but got...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code sample (remove sensitive tokens!)
      render: python
      placeholder: |
        from athm import ATHMovilClient
        client = ATHMovilClient(public_token="...")
        client.create_payment(...)  # Error occurs here
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version Info
      description: athm version and Python version
      placeholder: "athm 1.0.0, Python 3.11"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Searched existing issues
          required: true
        - label: Removed sensitive information
          required: true
